version: "2.1"

volumes:
  deconz-data:

services:

  deconz:
    image: deconzcommunity/deconz:2.13.04
    network_mode: host
    restart: always
    volumes:
      - "deconz-data:/opt/deCONZ"
    devices:
      - /dev/ttyAMA0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - TZ=Europe/Oslo

  telegraf:
    build: ./balena-telegraf
    pid: "host"
    network_mode: "host"
    privileged: true
    labels:
      io.resin.features.balena-socket: '1'
    environment:
      - INFLUX_URL=http://10.0.1.202:8086
      - INFLUX_DB=telegraf

